src/Entity/Command.php
<?php

namespace App\Entity;

use App\Repository\CommandRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandRepository::class)]
class Command
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $delivred_at = null;

    #[ORM\Column]
    private ?int $quantity = null;

    #[ORM\Column]
    private ?int $total = null;

    #[ORM\ManyToOne(inversedBy: 'commands')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Product $product = null;

    #[ORM\ManyToOne(inversedBy: 'commands')]
    #[ORM\JoinColumn(nullable: false)]
    private ?ApplicationUser $for_user = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Address $address = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getDelivredAt(): ?\DateTimeImmutable
    {
        return $this->delivred_at;
    }

    public function setDelivredAt(?\DateTimeImmutable $delivred_at): static
    {
        $this->delivred_at = $delivred_at;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): static
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getTotal(): ?int
    {
        return $this->total;
    }

    public function setTotal(int $total): static
    {
        $this->total = $total;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): static
    {
        $this->product = $product;

        return $this;
    }

    public function getForUser(): ?ApplicationUser
    {
        return $this->for_user;
    }

    public function setForUser(?ApplicationUser $for_user): static
    {
        $this->for_user = $for_user;

        return $this;
    }

    public function getAddress(): ?Address
    {
        return $this->address;
    }

    public function setAddress(Address $address): static
    {
        $this->address = $address;

        return $this;
    }
}

src/Form/CommandType.php
<?php

namespace App\Form;

use App\Entity\Address;
use App\Entity\ApplicationUser;
use App\Entity\Command;
use App\Entity\Product;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('quantity')
            ->add('address', AddressType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Command::class,
        ]);
    }
}

src/Controller/CommandController.php
<?php

namespace App\Controller;

use App\Entity\Command;
use App\Entity\Product;
use App\Form\CommandType;
use App\Repository\ApplicationUserRepository;
use App\Repository\CommandRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/command')]
class CommandController extends AbstractController
{
    #[Route('/product/{id}/new', name: 'app_command_new', methods: ['GET', 'POST'])]
    public function new(
        Request                $request,
        EntityManagerInterface $entityManager,
        Product                $product,
        ApplicationUserRepository $applicationUserRepository
    ): Response
    {
        $command = new Command();
        $user = $this->getUser();
        $applicationUser = $applicationUserRepository->findOneBy(['username' => $user->getUserIdentifier()]);
        $default_address = $applicationUser->getAddress();
        if ($default_address) {
            $command->setAddress($default_address);
        }

        $form = $this->createForm(CommandType::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $command->setProduct($product);
            $command->setForUser($this->getUser());
            $command->setCreatedAt(new \DateTimeImmutable());
            $command->setStatus('pending');
            $command->setTotal($product->getPrice() * $command->getQuantity());
            $entityManager->persist($command);
            $entityManager->flush();

            return $this->redirectToRoute('app_command_show', ['id' => $command->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->render('command/new.html.twig', [
            'command' => $command,
            'form' => $form,
        ]);
    }


    #[Route('/my-cart', name: 'app_my_cart', methods: ['GET'])]
    public function my_cart(CommandRepository $commandRepository): Response
    {
        return $this->render('command/my_cart.html.twig', [
            'commands' => $commandRepository->findBy(['for_user' => $this->getUser()])
        ]);
    }

    #[Route('/{id}/accept', name: 'app_command_accept', methods: ['GET'])]
    public function accept(Command $command, EntityManagerInterface $entityManager): Response
    {
        if ($command->getProduct()->getCreatedBy() !== $this->getUser()) {
            throw $this->createAccessDeniedException();
        }
        $command->setStatus('accepted');
        $product = $command->getProduct();
        $product->setQuantity($product->getQuantity() - $command->getQuantity());
        if ($product->getQuantity() < 0) {
            $this->addFlash('error', 'Not enough quantity');
            return $this->redirectToRoute('app_product_commands', ['id' => $command->getProduct()->getId()], Response::HTTP_SEE_OTHER);
        }
        $entityManager->flush();
        return $this->redirectToRoute('app_product_commands', ['id' => $command->getProduct()->getId()], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}/delivered', name: 'app_command_delivered', methods: ['GET'])]
    public function delivered(Command $command, EntityManagerInterface $entityManager): Response
    {
        if ($command->getProduct()->getCreatedBy() !== $this->getUser()) {
            throw $this->createAccessDeniedException();
        }
        $command->setStatus('delivered');
        $command->setDelivredAt(new \DateTimeImmutable());
        $entityManager->flush();
        return $this->redirectToRoute('app_product_commands', ['id' => $command->getProduct()->getId()], Response::HTTP_SEE_OTHER);
    }

    #[Route('/product/{id}', name: 'app_product_commands', methods: ['GET'])]
    public function product_commands(Product $product, CommandRepository $commandRepository): Response
    {
        if ($product->getCreatedBy() !== $this->getUser()) {
            throw $this->createAccessDeniedException();
        }
        return $this->render('command/product_commands.html.twig', [
            'commands' => $commandRepository->findBy(['product' => $product]),
            'product' => $product
        ]);
    }

    #[Route('/{id}', name: 'app_command_show', methods: ['GET'])]
    public function show(Command $command): Response
    {
        return $this->render('command/show.html.twig', [
            'command' => $command,
        ]);
    }

    #[Route('/{id}', name: 'app_command_delete', methods: ['POST'])]
    public function delete(Request $request, Command $command, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $command->getId(), $request->getPayload()->get('_token'))) {
            if ($command->getForUser() !== $this->getUser()) {
                throw $this->createAccessDeniedException();
            }
            $product = $command->getProduct();
            $product->setQuantity($product->getQuantity() + $command->getQuantity());
            $entityManager->remove($command);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_main', [], Response::HTTP_SEE_OTHER);
    }

}

templates/command/_delete_form.html.twig
<form method="post" action="{{ path('app_command_delete', {'id': command.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ command.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/command/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/command/my_cart.html.twig
{% extends 'base.html.twig' %}

{% block title %}Command index{% endblock %}

{% block body %}
    <style>
        table,tr,th,td{
            border: 1px solid black;
            border-collapse: collapse;
            padding: 10px;
        }
    </style>
    <div class="container mt-5">
    <h1 class="">My Cart</h1>
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead class="table-dark">
                <tr>
                    <th>Id</th>
                    <th>Status</th>
                    <th>Created At</th>
                    <th>Delivered At</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for command in commands %}
                    <tr>
                        <td>{{ command.id }}</td>
                        <td>{{ command.status }}</td>
                        <td>{{ command.createdAt ? command.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                        <td>{{ command.delivredAt ? command.delivredAt|date('Y-m-d H:i:s') : '' }}</td>
                        <td>{{ command.quantity }}</td>
                        <td>{{ command.total }}</td>
                        <td>
                            <a href="{{ path('app_command_show', {'id': command.id}) }}" class="btn btn-primary btn-sm">Show</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="7" class="text-center">No records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/command/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Command{% endblock %}

{% block body %}
    <div class="container">
        <h1>Create new Command</h1>
        {{ include('command/_form.html.twig') }}
    </div>
{% endblock %}

templates/command/product_commands.html.twig
{% extends 'base.html.twig' %}

{% block title %}Command index{% endblock %}

{% block body %}
    <style>
        table,tr,th,td{
            border: 1px solid black;
            border-collapse: collapse;
            padding: 10px;
        }
    </style>
    <div class="container mt-5">
    <h1 class="text-center">Commands for : {{ product.name }}</h1>
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead class="table-dark">
                <tr>
                    <th>Id</th>
                    <th>Status</th>
                    <th>Created At</th>
                    <th>Delivered At</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>For User</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for command in commands %}
                    <tr>
                        <td>{{ command.id }}</td>
                        <td>{{ command.status }}</td>
                        <td>{{ command.createdAt ? command.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                        <td>{{ command.delivredAt ? command.delivredAt|date('Y-m-d H:i:s') : '' }}</td>
                        <td>{{ command.quantity }}</td>
                        <td>{{ command.total }}</td>
                        <td>{{ command.forUser.username }}</td>
                        <td>
                            <a href="{{ path('app_command_show', {'id': command.id}) }}" class="btn btn-primary btn-sm">Show</a>
                            {% if command.status == 'pending' %}
                                <a href="{{ path('app_command_accept', {'id': command.id}) }}" class="btn btn-success btn-sm">Accept</a>
                                {% elseif command.status == 'accepted' %}
                                <a href="{{ path('app_command_delivered', {'id': command.id}) }}" class="btn btn-success btn-sm">Deliver</a>
                            {% endif %}
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="8" class="text-center">No records found</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

templates/command/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Command{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1>Command</h1>
        <table class="table">
            <tbody>
            <tr>
                <th>Id</th>
                <td>{{ command.id }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ command.status }}</td>
            </tr>
            <tr>
                <th>Created At</th>
                <td>{{ command.createdAt ? command.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Delivered At</th>
                <td>{{ command.delivredAt ? command.delivredAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td>{{ command.quantity }}</td>
            </tr>
            <tr>
                <th>Total</th>
                <td>{{ command.total }}</td>
            </tr>
            <tr>
                <th>For User</th>
                <td>{{ command.forUser.username }}</td>
            </tr>

            <tr>
                <th>To product</th>
                <td>
                    <a href="{{ path('app_product_show', {'id': command.product.id}) }}">{{ command.product.name }}</a>
                </td>
            </tr>
            </tbody>
        </table>
        {% if app.user and app.user.username == command.forUser.username %}
            {{ include('command/_delete_form.html.twig') }}
        {% endif %}
    </div>
{% endblock %}