src/Entity/ProductReport.php
<?php

namespace App\Entity;

use App\Repository\ProductReportRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductReportRepository::class)]
class ProductReport
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'productReports')]
    #[ORM\JoinColumn(nullable: false)]
    private ?ApplicationUser $by_user = null;

    #[ORM\ManyToOne(inversedBy: 'productReports')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Product $to_product = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $reason = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getByUser(): ?ApplicationUser
    {
        return $this->by_user;
    }

    public function setByUser(?ApplicationUser $by_user): static
    {
        $this->by_user = $by_user;

        return $this;
    }

    public function getToProduct(): ?Product
    {
        return $this->to_product;
    }

    public function setToProduct(?Product $to_product): static
    {
        $this->to_product = $to_product;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getReason(): ?string
    {
        return $this->reason;
    }

    public function setReason(string $reason): static
    {
        $this->reason = $reason;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }
}

src/Form/ProductReportType.php
<?php

namespace App\Form;

use App\Entity\ApplicationUser;
use App\Entity\Product;
use App\Entity\ProductReport;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductReportType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('reason')
            ->add('description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ProductReport::class,
        ]);
    }
}

src/Controller/ProductReportController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Entity\ProductReport;
use App\Form\ProductReportType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/profile/report/product')]
class ProductReportController extends AbstractController
{

    #[Route('/new/{id}', name: 'app_product_report_new', methods: ['GET', 'POST'])]
    public function new(
                        Product $product,
                        Request $request,
                        EntityManagerInterface $entityManager
    ): Response
    {
        $productReport = new ProductReport();
        $form = $this->createForm(ProductReportType::class, $productReport);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $productReport->setToProduct($product);
            $productReport->setStatus("pending");
            $productReport->setByUser($this->getUser());
            $entityManager->persist($productReport);
            $entityManager->flush();

            return $this->redirectToRoute('app_product_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('product_report/new.html.twig', [
            'product_report' => $productReport,
            'form' => $form,
        ]);
    }

}

templates/product_report/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-danger">{{ button_label|default('report') }}</button>
{{ form_end(form) }}

templates/product_report/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ProductReport index{% endblock %}

{% block body %}
    <div class="container mt-3">
    <h1>Reports Requests</h1>
    <table class="table table-bordered table-striped">
        <thead class="table-dark">
        <tr>
            <th>Id</th>
            <th>Description</th>
            <th>Reason</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for product_report in product_reports %}
            <tr>
                <td>{{ product_report.id }}</td>
                <td>{{ product_report.description }}</td>
                <td>{{ product_report.reason }}</td>
                <td>
                    <a href="{{ path('app_product_report_show', {'id': product_report.id}) }}" class="btn btn-primary btn-sm">Show</a>
                    <a href="{{ path('app_product_report_reject', {'id': product_report.id}) }}" class="btn btn-success btn-sm">Reject</a>
                    <a href="{{ path('app_product_report_accept', {'id': product_report.id}) }}" class="btn btn-danger btn-sm">Ban</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5" class="text-center">No records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

templates/product_report/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ProductReport{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h1>Create new ProductReport</h1>
        {{ include('product_report/_form.html.twig') }}
        <a class="btn btn-secondary" href="{{ path('app_product_report_index') }}">back to list</a>
    </div>
{% endblock %}

templates/product_report/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ProductReport{% endblock %}

{% block body %}
    <div class="container mt-3">
    <h1>Report Request : {{ product_report.id }}</h1>
    <table class="table table-bordered table-striped">
        <tbody>
        <tr>
            <th scope="row">Id</th>
            <td>{{ product_report.id }}</td>
        </tr>
        <tr>
            <th scope="row">Description</th>
            <td>{{ product_report.description }}</td>
        </tr>
        <tr>
            <th scope="row">Reason</th>
            <td>{{ product_report.reason }}</td>
        </tr>
        <tr>
            <th scope="row">Product</th>
            <td style="text-decoration: underline">
                <a href="{{ path('app_product_show', {'id': product_report.toProduct.id}) }}">{{ product_report.toProduct.name }}</a>
            </td>
        </tr>
        <tr>
            <th scope="row">Status</th>
            <td>{{ product_report.status }}</td>
        </tr>
        <tr>
            <th scope="row">Actions</th>
            <td>
                <a href="{{ path('app_product_report_reject', {'id': product_report.id}) }}" class="btn btn-success btn-sm">Reject</a>
                <a href="{{ path('app_product_report_accept', {'id': product_report.id}) }}" class="btn btn-danger btn-sm">Ban</a>
            </td>
        </tr>
        </tbody>
    </table>
    <a class="btn btn-secondary" href="{{ path('app_product_report_index') }}">back to list</a>
    </div>
{% endblock %}